Restrict Base64 encryption for Kitkat and above It will otherwise throw a NoClassDefFoundError as the StandardCharsets.UTF_8 is introduced in Kitkat
Signed-off-by: sunilpaulmathew <sunil.kde@gmail.com>